# Generated by Django 5.2.3 on 2025-06-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('url', models.CharField(blank=True, help_text="Можно указать явный URL (например '/about/') или named URL (например 'about-page')", max_length=200, verbose_name='Ссылка (URL)')),
                ('menu_name', models.CharField(help_text='Идентификатор меню для template tag', max_length=50, verbose_name='Название меню')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order', 'name'],
            },
        ),
    ]
